.TH tinysshd-makekey 1
.SH NAME
tinysshd-makekey \- create TinySSH key-directory
.SH SYNOPSIS
.B tinysshd-makekey
.I keydir
.SH DESCRIPTION
.B tinysshd-makekey
TODO
.SH OPTIONS
.TP
.I keydir
directory for TinySSH keys
.SH SEE ALSO
.BR tinysshd (8),
.BR tinysshd-printkey (1)
.sp
.nf
https://tinyssh.org/
.fi
