.TH tinysshd 8
.SH NAME
tinysshd \- Tiny SSH daemon
.SH SYNOPSIS
.B tinysshd
[ options ]
.I keydir
.SH DESCRIPTION
.B tinysshd
is tiny SSH server which implement 'less'.
.sp
.B tinysshd
supports only secure crypto (min. 128-bit security, protected against cache-timing attacks)
.sp
.B tinysshd
doesn't implement unnecessary features (such SSH1 protocol, compression, scp, sftp, ...)
.sp
.B tinysshd
doesn't implement older crypto (such RSA, DSA, HMAC-MD5, HMAC-SHA1, 3DES, RC4, ...)
.sp
.B tinysshd
doesn't implement unsafe features (such password or hostbased authentication)
.sp
.B tinysshd
doesn't use dynamic memory allocation (no allocation failures, etc.)
.SH OPTIONS
.TP
.B \-q
no error messages
.TP
.B \-Q
print error messages (default)
.TP
.B \-v
print extra information
.TP
.B \-o
enable older standardized crypto - ecdsa-sha2-nistp256, ecdh-sha2-nistp256, aes128-ctr, aes256-ctr, hmac-sha2-256
.TP
.B \-O
disable older standardized crypto (default)
.TP
.B \-s
enable state-of-the-art crypto - ssh-ed25519, curve25519-sha256@libssh.org, chacha20-poly1305@openssh.com (default)
.TP
.B \-S
disable state-of-the-art crypto
.TP
.B \-p
enable post-quantum crypto - TODO, TODO, chacha20-poly1305@openssh.com
.TP
.B \-P
disable post-quantum crypto
.TP
.B \-l
use syslog instead of standard error output (useful for running from inetd)
.TP
.B \-L
don't use syslog, use standard error output (default)
.TP
.B \-x \fIname=command
add subsystem command (e.g.: sftp=/usr/libexec/openssh/sftp-server)
.TP
.I keydir
directory containing TinySSH keys, typically /etc/tinyssh/sshkeydir
.SH EXAMPLES
.TP
.B TCPSERVER
tcpserver \-HRDl0 0.0.0.0 22 /usr/sbin/tinysshd \-v /etc/tinyssh/sshkeydir &
.TP
.B BUSYBOX
busybox tcpsvd 0 22 tinysshd \-v /etc/tinyssh/sshkeydir &
.TP
.B INETD
.RS 4
/etc/inetd.conf:
.RS 4
ssh stream tcp nowait root /usr/sbin/tinysshd tinysshd \-l \-v /etc/tinyssh/sshkeydir
.RE
.RE
.TP
.B SYSTEMD
.RS 4
tinyssh-server.socket:
.RS 4
.nf
[Unit]
Description=TinySSH server socket
Before=tinyssh-server.service
Conflicts=tinyssh-server.service

[Socket]
ListenStream=22
Accept=yes

[Install]
WantedBy=sockets.target
.fi
.RE
.RE
.sp
.RS 4
tinyssh-server@.service:
.RS 4
.nf
[Unit]
Description=Tiny SSH server
After=network.target auditd.service

[Service]
EnvironmentFile=-/etc/default/tinyssh-server
ExecStart=/usr/sbin/tinysshd \-v /etc/tinyssh/sshkeydir
KillMode=process
Restart=on-failure
StandardInput=socket
StandardError=journal

[Install]
WantedBy=multi-user.target
Alias=tinyssh-server.service
.fi
.RE
.RE
.SH SEE ALSO
.BR tinysshd-makekey (1),
.BR tinysshd-printkey (1)
.sp
.nf
https://tinyssh.org/
.fi
