.TH tinysshd\-printkey 8
.SH NAME
tinysshd\-printkey \- print TinySSH public\-keys
.SH SYNOPSIS
.B tinysshd\-printkey
.I keydir
.SH DESCRIPTION
.B tinysshd\-printkey
prints TinySSH public\-keys in base64 format
.SH OPTIONS
.TP
.I keydir
directory containing TinySSH keys, typically /etc/tinyssh/sshkeydir
.SH EXAMPLE
tinysshd\-printkey /etc/tinyssh/sshkeydir
.SH SEE ALSO
.BR tinysshd (8),
.BR tinysshd\-makekey (8)
.sp
.nf
https://tinyssh.org/
.fi
