.TH tinysshd\-makekey 8
.SH NAME
tinysshd\-makekey \- create TinySSH key\-directory
.SH SYNOPSIS
.B tinysshd\-makekey
[ options ]
.I keydir
.SH DESCRIPTION
.B tinysshd\-makekey
safely creates secret\-keys and appropriate public\-keys in directory
.I keydir
.SH OPTIONS
.TP
.B \-q
no error messages
.TP
.B \-Q
print error messages (default)
.TP
.TP
.I keydir
directory for TinySSH keys, typically /etc/tinyssh/sshkeydir
.SH EXAMPLE
tinysshd\-makekey /etc/tinyssh/sshkeydir
.SH SEE ALSO
.BR tinysshd (8),
.BR tinysshd\-printkey (8)
.sp
.nf
https://tinyssh.org/
.fi
