#!/bin/sh
exec 2>&1

[ -f /etc/default/tinyssh-run ] && . /etc/default/tinyssh-run

if [ x"${IP}" = x ]; then
  IP=0.0.0.0
  export IP
fi

if [ x"${PORT}" = x ]; then
  PORT=22
  export PORT
fi

tcpserver=tcpserver
if [ -x /usr/sbin/tinysshd-tcpserver ]; then
  tcpserver=/usr/sbin/tinysshd-tcpserver
fi

#TinySSH key
[ -d /etc/tinyssh/sshkeydir ] || \
  (
    /usr/sbin/tinysshd-random32 > /dev/urandom || :
    /usr/sbin/tinysshd-makekey /etc/tinyssh/sshkeydir
  )

echo "Starting TinySSH using TCP transport: ${IP}:${PORT}" >&2
/usr/sbin/tinysshd-printkey /etc/tinyssh/sshkeydir >&2
 
exec "${tcpserver}" -HRDl0 "${IP}" "${PORT}" /usr/sbin/tinysshd ${OPTIONS} /etc/tinyssh/sshkeydir
