/*
20140225
Jan Mojzis
Public domain.
*/

#include <sys/types.h>
#include <unistd.h>
#include <sys/time.h>
#include "randombytes.h"
#include "crypto.h"
#include "purge.h"
#include "sshcrypto.h"

/* Nothing to do. */
void sshcrypto_init(void) {
}

/*
Remove sentitive data from allocated memory.
*/
void sshcrypto_purge(void) {

    long long i;

    /* kex */
    for (i = 0; sshcrypto_kexs[i].name; ++i) {
        purge(&sshcrypto_kexs[i], sizeof(struct sshcrypto_kex));
    }

    /* key */
    for (i = 0; sshcrypto_keys[i].name; ++i) {
        purge(&sshcrypto_keys[i], sizeof(struct sshcrypto_key));
    }

    /* cipher */
    for (i = 0; sshcrypto_ciphers[i].name; ++i) {
        purge(&sshcrypto_ciphers[i], sizeof(struct sshcrypto_cipher));
    }
}


/*
The 'sshcrypto_random32(x)' function generates 256bit random string.
It's generated by hashing a "secret initial value (seed)".
Seed is taken from OS random generator and is also
filled using pseudorandom bytes (time, process id)
as a simple protection against bad random generators.
*/

void sshcrypto_random32(unsigned char *x) {

    unsigned char seed[64];
    struct timeval t;

    randombytes(seed, sizeof seed);
    gettimeofday(&t, (struct timezone *)0);
    x[33] = getpid()  + t.tv_usec; t.tv_usec >>= 8;
    x[34] = getppid() + t.tv_usec; t.tv_usec >>= 8;
    crypto_hash_sha512(seed, seed, 64);
    byte_copy(x, 32, seed);
    purge(seed, sizeof seed);
}
