#!/bin/sh -e

okabi | (
  while read abi
  do
    (
    sh list
    ) | (
      while read target source
      do
        okc-$abi | (
          while read c
          do
            libs=`"oklibs-$abi"`
            [ -f "include/$abi/$target" ] && continue
            echo "=== `date` ===   $abi trying $source as $target under $c..." >&2
            rm -f "$source" "$target.tmp" 
            $c -o "$source" "$source.c" $libs 2>/dev/null || continue
            ./$source > "$target.tmp" 2>/dev/null || continue
            mkdir -p "include/$abi"
            cp "$target.tmp" "include/$abi/$target"
          done
        )
      done
    )
  done
)
