#!/bin/sh -e

#crypto_uint*/crypto_int*
echo 'crypto_int8.h crypto_int8.h-char'
echo 'crypto_uint8.h crypto_uint8.h-char'

echo 'crypto_int16.h crypto_int16.h-short'
echo 'crypto_uint16.h crypto_uint16.h-short'

echo 'crypto_int32.h crypto_int32.h-int'
echo 'crypto_int32.h crypto_int32.h-long'
echo 'crypto_uint32.h crypto_uint32.h-int'
echo 'crypto_uint32.h crypto_uint32.h-long'

echo 'crypto_int64.h crypto_int64.h-longlong'
echo 'crypto_int64.h crypto_int64.h-long'
echo 'crypto_int64.h crypto_int64.h-attr'
echo 'crypto_uint64.h crypto_uint64.h-longlong'
echo 'crypto_uint64.h crypto_uint64.h-long'
echo 'crypto_uint64.h crypto_uint64.h-attr'

#mlock
echo 'hasmlock.h hasmlock.h-yes'
echo 'hasmlock.h default.h-no'

#util/libutil
echo 'haslibutilh.h haslibutilh.h-yes' 
echo 'haslibutilh.h default.h-no' 
echo 'hasutilh.h hasutilh.h-yes' 
echo 'hasutilh.h default.h-no' 

#openpty/login_tty
echo 'hasopenpty.h hasopenpty.h-yes'
echo 'hasopenpty.h default.h-no'
echo 'haslogintty.h haslogintty.h-yes'
echo 'haslogintty.h default.h-no'

#utmpx
echo 'hasutmpx.h hasutmpx.h-yes'
echo 'hasutmpx.h default.h-no'
echo 'hasutmpxupdwtmpx.h hasutmpxupdwtmpx.h-yes'
echo 'hasutmpxupdwtmpx.h default.h-no'
echo 'hasutmpxsyslen.h hasutmpxsyslen.h-yes'
echo 'hasutmpxsyslen.h default.h-no'

#utmp
echo 'hasutmp.h hasutmp.h-yes'
echo 'hasutmp.h default.h-no'
echo 'hasutmpname.h hasutmpname.h-yes'
echo 'hasutmpname.h default.h-no'
echo 'hasutmpuser.h hasutmpuser.h-yes'
echo 'hasutmpuser.h default.h-no'
echo 'hasutmphost.h hasutmphost.h-yes'
echo 'hasutmphost.h default.h-no'
echo 'hasutmptime.h hasutmptime.h-yes'
echo 'hasutmptime.h default.h-no'
echo 'hasutmptv.h hasutmptv.h-yes'
echo 'hasutmptv.h default.h-no'
echo 'hasutmppid.h hasutmppid.h-yes'
echo 'hasutmppid.h default.h-no'
echo 'hasutmptype.h hasutmptype.h-yes'
echo 'hasutmptype.h default.h-no'
echo 'hasutmplogwtmp.h hasutmplogwtmp.h-yes'
echo 'hasutmplogwtmp.h default.h-no'
echo 'hasutmploginlogout.h hasutmploginlogout.h-yes'
echo 'hasutmploginlogout.h default.h-no'

#order
echo 'order.h order.h-little'
echo 'order.h order.h-big'
echo 'order.h default.h-no'
