#!/bin/sh -e

#__asm__ __volatile__ ...
echo 'hasasmvolatilememory.h hasasmvolatilememory.h-yes'
echo 'hasasmvolatilememory.h default.h-no'

#mlock
echo 'hasmlock.h hasmlock.h-yes'
echo 'hasmlock.h default.h-no'

#util/libutil
echo 'haslibutilh.h haslibutilh.h-yes' 
echo 'haslibutilh.h default.h-no' 
echo 'hasutilh.h hasutilh.h-yes' 
echo 'hasutilh.h default.h-no' 

#openpty/login_tty
echo 'hasopenpty.h hasopenpty.h-yes'
echo 'hasopenpty.h default.h-no'
echo 'haslogintty.h haslogintty.h-yes'
echo 'haslogintty.h default.h-no'

#utmpx
echo 'hasutmpx.h hasutmpx.h-yes'
echo 'hasutmpx.h default.h-no'
echo 'hasutmpxupdwtmpx.h hasutmpxupdwtmpx.h-yes'
echo 'hasutmpxupdwtmpx.h default.h-no'
echo 'hasutmpxsyslen.h hasutmpxsyslen.h-yes'
echo 'hasutmpxsyslen.h default.h-no'

#utmp
echo 'hasutmp.h hasutmp.h-yes'
echo 'hasutmp.h default.h-no'
echo 'hasutmpname.h hasutmpname.h-yes'
echo 'hasutmpname.h default.h-no'
echo 'hasutmpuser.h hasutmpuser.h-yes'
echo 'hasutmpuser.h default.h-no'
echo 'hasutmphost.h hasutmphost.h-yes'
echo 'hasutmphost.h default.h-no'
echo 'hasutmptime.h hasutmptime.h-yes'
echo 'hasutmptime.h default.h-no'
echo 'hasutmptv.h hasutmptv.h-yes'
echo 'hasutmptv.h default.h-no'
echo 'hasutmppid.h hasutmppid.h-yes'
echo 'hasutmppid.h default.h-no'
echo 'hasutmptype.h hasutmptype.h-yes'
echo 'hasutmptype.h default.h-no'
echo 'hasutmplogwtmp.h hasutmplogwtmp.h-yes'
echo 'hasutmplogwtmp.h default.h-no'
echo 'hasutmploginlogout.h hasutmploginlogout.h-yes'
echo 'hasutmploginlogout.h default.h-no'

#order
echo 'order.h order.h-runtime-little'
echo 'order.h order.h-runtime-big'
echo 'order.h default.h-no'

#limits
echo 'haslimits.h haslimits.h-yes'
echo 'haslimits.h default.h-no'
